name: Build and test

on: [push, pull_request]

env:
    CI: true

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npx tsc --noEmit
            - run: npm test
